LMS/Controllers/KlassController.cs
using LMS.CustomAttributes;
using LMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace LMS.Controllers
{
	[Authorize]
    public class KlassController : Controller {
		private Repositories.KlassRepository repo = new Repositories.KlassRepository();
        // GET: Klass
		[Authorize(Roles="Teacher")]
        public ActionResult Index(){
			return View(repo.GetAll());
        }

        [Authorize]
        public ActionResult ShowMyClasses()
        {
            return View(repo.GetMyClasses(User.Identity.GetUserId()));
        }

        [AttendsKlass(ParamFrom = "2")]
        public ActionResult Details(int Id) {
			return View(new KlassDetailsViewModel(repo.GetSpecific(Id), repo.GetNonMembers(Id)));
		}

		[Authorize(Roles="Teacher")]
		public JsonResult RemoveKlassMember(int Id, string UId) {
			bool success = repo.RemoveKlassMember(Id, UId);
			return Json(new { Removed = success }, JsonRequestBehavior.AllowGet);
		}

        [AttendsKlass(ParamFrom = "2")]
        public JsonResult GetNonMembers(int Id) {
			return Json(repo.GetNonMembers(Id).Select(u => new UserViewModel(u)), JsonRequestBehavior.AllowGet);
		}

        [AttendsKlass(ParamFrom = "2")]
        public JsonResult GetMembers(int Id) {
			var klass = repo.GetSpecific(Id);
			if (klass == null) return null;
			else return Json(klass.Members.Select(u => new UserViewModel(u)), JsonRequestBehavior.AllowGet);
		}

		[Authorize(Roles="Teacher")]
		[HttpGet]
		public ActionResult Create() {
			return View();
		}

		[Authorize(Roles = "Teacher")]
		[HttpPost]
		public ActionResult Create(Klass model) {
			model.Schedule = new KlassSchedule();
			if (ModelState.IsValid) {
				repo.Add(model);
				return RedirectToAction("Index");
			}
			return View(model);
		}

		[Authorize(Roles="Teacher")]
		public JsonResult AddKlassMember(int Id, string UId) {

			bool success = repo.AddKlassMember(Id, UId);

			return Json(new { Added = success}, JsonRequestBehavior.AllowGet);
		}

		[Authorize(Roles="Teacher")]
		public ActionResult Delete(int ID) {
			repo.Delete(ID);
			return RedirectToAction("Index");
		}
	}
}

LMS/Controllers/SharedController.cs
using LMS.Models;
using LMS.Repositories;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
	[Authorize]
    public class SharedFilesController : FileController<SharedFile>
    {
		public ActionResult Share(int? kID)
		{
			//var repo = new KlassRepository();
			//var klasses = repo.GetMyClasses(User.Identity.GetUserId()).Select(k => new SelectListItem { Value = k.ID.ToString(), Text = k.Name });
			//var model = new UploadFileViewModel();
			//model.KlassList = klasses;
			var uID = User.Identity.GetUserId();

			if (kID.HasValue) {
				var asdf = new AccessRepository();
				if (asdf.IsStudent(uID) && !asdf.UserAttendsKlass(uID, kID.Value))
					return View("AccessDenied");
			}

			var klassRepo = new KlassRepository();
			var klasses = kID == null ?
				klassRepo.GetMyClasses(uID)/*.Select(k => new SelectListItem { Value = k.ID.ToString(), Text = k.Name });*/
				: new List<Klass>() { klassRepo.GetSpecific(kID.Value) };
			var model = new UploadFileViewModel();
			model.KlassList = klasses.Select(k => new SelectListItem { Value = k.ID.ToString(), Text = k.Name });
			model.Files = klasses.SelectMany(k => k.Shared);

			ViewBag.KlassID = kID;

			return View("Share", model);
		}

		public override dynamic Download(int? ID)
		{
			int ID2;
			if (ID == null) { return View("AccessDenied"); }
			else ID2 = (int) ID;
			var Arepo = new AccessRepository();
			var file = repo.GetSpecific(ID2);
			if (file == null) { return View("AccessDenied"); }
			if (Arepo.UserAttendsKlass(User.Identity.GetUserId(), file.KlassID))
			{
				return File(file.Content, file.ContentType, file.FileName);
			}
			else
			{
				return View("AccessDenied");
			}
		}
    }
}

LMS/Views/Klass/Create.cshtml
@model LMS.Models.Klass

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Klass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/Klass/Details.cshtml
@using LMS.Models
@model LMS.Models.KlassDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Manage @Model.Klass.Name</h2>

<div ng-app="KlassApp" ng-controller="KlassMemberTable" ng-init="KlassId = @Model.Klass.ID">
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-12">
            @Html.ActionLink("Shared files", "Share", "SharedFiles", new { kID = @Model.Klass.ID }, new { @class = "btn btn-primary" })
            @{
                if (HttpContext.Current.User.IsInRole("Teacher"))
                {
                    <i>&nbsp;</i> @Html.ActionLink("Submitted Assignments", "Index", "TeacherSubmission", new { KlassID = @Model.Klass.ID }, new { @class = "btn btn-primary" })
                }
            }

            <i>&nbsp;</i><a class="btn btn-primary" href="/Schedule/KlassSchedule/@(Model.Klass.ID)">Schedule</a>
            <button ng-click="EditingActive = !EditingActive" class="btn btn-primary pull-right">{{EditingActive ? "Stop editing" : "Edit participitation"}}</button>
            <div @*fuck html, that's why*@
                 ng-show="EditingActive"
                 ng-init="showshit = false; NonMembersTableAppends.push('&lt;td&gt;&lt;button class=&quot;btn btn-info&quot;ng-click=&quot;Funcs.AddMember(user)&quot;&gt;Join Class&lt;/button&gt;&lt;/td&gt;')">

                <button class="btn btn-primary pull-right" style="margin-top: 10px;margin-bottom:10px;" ng-click="showshit = !showshit">Add members</button>
                <div ng-show="showshit" ng-init="GetData('getnonmembers?id=' + '@Model.Klass.ID', NonMembers)">
                    <div ng-controller="UserListController" ng-init="tag='NonMembers'; GetShit()">
                        @Html.Partial("~/Views/Users/UserListPartial.cshtml")
                    </div>
                </div>
            </div>

            <div ng-init="MembersTableAppends.push('&lt;td ng-show=&quot;EditingActive&quot;&gt;&lt;button class=&quot;btn btn-warning&quot;ng-click=&quot;Funcs.RemoveMember(user)&quot;&gt;Leave Class&lt;/button&gt;&lt;/td&gt;')">
                <div ng-init="userList={data: null}; GetData('getmembers?id=' + '@Model.Klass.ID', Members)">
                    <div ng-controller="UserListController" ng-init="tag='Members'; GetShit()">
                        @Html.Partial("~/Views/Users/UserListPartial.cshtml")
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Back to Classes / Courses", "Index", new { }, new { @class="btn btn-primary" })
</p>

LMS/Views/Klass/Index.cshtml
@model IEnumerable<LMS.Models.Klass>

@{
    ViewBag.Title = "Index";
}

<h2>Manage Classes / Courses</h2>

<p>
    @Html.ActionLink("Create New", "Create" , new { }, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <h4>
                @Html.DisplayFor(modelItem => item.Name)
            </h4>
        </td>
        <td>
            @Html.ActionLink("Manage", "Details", new { id=item.ID }, new { @class = "btn btn-primary" }) &nbsp;
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

LMS/Views/Klass/ShowMyClasses.cshtml
@model IEnumerable<LMS.Models.Klass>
@using LMS.Repositories

@{
    ViewBag.Title = "My Classes/Courses";
}

<h2>My Classes/Courses</h2>

@foreach (var klass in Model) {
    <h2>@(klass.Name)&nbsp;&nbsp;<a class="btn btn-primary" href="/SharedFiles/Share?kID=@(klass.ID)">Shared files</a>&nbsp;&nbsp;<a class="btn btn-primary" href="/Schedule/KlassSchedule/@(klass.ID)">Schedule</a></h2>
    <h3>Teachers</h3>
    <table class="table">

		@{
			//Identity is a filthy whore bitch, that's why
			AccessRepository accessRepo = new AccessRepository();
		}
            @foreach (var member in klass.Members.Where(m => accessRepo.IsTeacher(m.Id)))
            {
                <tr>
                <td>
                    @member.FirstName
                    @member.LastName
                </td>
                <td> 
                    @member.Email</td>
                <td>
                    @member.PhoneNumber
                </td>
                </tr>
            }
		<tr>
            </table>
            <h3>Students</h3>
            <table class="table">
                @foreach (var member in klass.Members.Where(m => accessRepo.IsStudent(m.Id)))
                {
                    <tr>
                        <td>
                            @member.FirstName
                            @member.LastName
                        </td>
                        <td>
                            @member.Email
                        </td>
                        <td>
                            @member.PhoneNumber
                        </td>
                    </tr>
                }
            </table>

            }